#include<stdio.h>
#include<stdlib.h>
#include<unistd.h>

int main() {
    int random_numebrs[2];
    int pip;
    int n1[1];          // for reading 
    pip = pipe(random_numebrs);
    
    if (pip == -1) {   // Checking if the pipe is created 
        perror("Pipe : ");
        return -1;
    }
    
    pid_t pid,pid1; // for c1 and c2
    
    pid = fork();
    
    if(pid == 0){    // C1 child process
        for (int i = 0; i < 5 ; i++){        // C1 creats 5 random numbers 
            int num = rand()%100;
            write(random_numebrs[1], &num, sizeof(num));
        }
    }
    else {          // Parent process
        pid1 = fork();      // Parent creates another fork process
        
        if(pid1 == 0){      // C2 child process
            for (int i =0; i<5;i++){     // C2 creates 5 random numbers 
                int num = rand()%100;
                write(random_numebrs[1], &num, sizeof(num));
            }  
        }
        else{       // Parent process
            for(int i = 0 ; i < 10 ; i++){     // Reading out 10 Random numbers generated by 2 child process C1 and C2
                read(random_numebrs[0],n1, sizeof(n1));
                printf("Random Number %2d : %d\n",(i+1),n1[0]);
            }    
        }
    }
    return 0;
}
